### PR TITLE
Use cross-compilation for linux aarch64 and ppc64le

### PR DESCRIPTION
**Pull request by martin-g**
This PR is based on top of https://github.com/conda-forge/sirius-ms-feedstock/pull/20.
It changes the `build_platform` for linux_aarch64 and linux_pcc64le to linux_64, because TravisCI is very unreliable.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
The Linux aarch64 build fails due to missing `linux-aarch64.jar` for https://bio.informatik.uni-jena.de/repository/libs-oss/de/unijena/bioinf/cbc-java/cbc-java-native/2.10.8.2/

**Comment by martin-g** [comment]
Hmmm! Maybe this is not the real reason for the failure because there is no jar for `linux-ppc64le` too but its build passes!

**Comment by martin-g** [comment]
@mfleisch Could you please take a look here ? Thank you!

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge-admin, please ping team

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
@conda-forge/core Could you please help with the review and merge of this PR ? Thanks!

**Review by xhochy — APPROVED** [review]

**Pull request merged**
